# Generated by Django 3.2.9 on 2021-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isac_protocol', models.CharField(max_length=256)),
                ('isac_approved', models.BooleanField()),
                ('name', models.CharField(max_length=256)),
                ('protocol_title', models.CharField(max_length=1024)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
