# Generated by Django 3.2.9 on 2021-12-16 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='database_builder_state',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Complete')], default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='input_directory',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VariableSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('index_date', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='VariableExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('state', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Running'), (2, 'Complete')], default=0)),
                ('variable_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.variableset')),
            ],
        ),
    ]
