# Generated by Django 3.1 on 2022-01-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220120_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isac_protocol',
            field=models.CharField(max_length=9),
        ),
    ]
